home:
  build: .
  dockerfile: ./test/home/Dockerfile
  working_dir: /labs
  entrypoint: /labs/test/home/entrypoint.sh
  volumes:
    - ./labs:/labs/labs:ro
    - ./test/log:/var/log/test
    - ./test:/labs/test:ro
  links:
    - labs

labs:
  build: ./test/labs
  command: /usr/sbin/sshd -D -E /var/log/sshd.log
