home:
  build: ./test/home
  volumes:
    - .:/labs-ro:ro
    - ./test/log:/var/log/test
  entrypoint: /labs-ro/test/home/entrypoint.sh
  links:
    - labs

labs:
  build: ./test/labs
  command: /usr/sbin/sshd -D -E /var/log/sshd.log
